# Mountain home color theme

[colors.primary]
background = "#0f0f0f"
foreground = "#f0f0f0"

[colors.normal]
black   = "#262626"
red     = "#ac8a8c"
green   = "#8aac8b"
yellow  = "#aca98a"
blue    = "#8f8aac"
magenta = "#ac8aac"
cyan    = "#8aabac"
white   = "#e7e7e7"

[colors.bright]
black   = "#4c4c4c"
red     = "#c49ea0"
green   = "#9ec49f"
yellow  = "#c4c19e"
blue    = "#a39ec4"
magenta = "#c49ec4"
cyan    = "#9ec3c4"
white   = "#f5f5f5"

[window]
opacity = 1

padding.x = 32 
padding.y = 24 
dynamic_padding = true

decorations = "None"
dynamic_title = true
decorations_theme_variant = "Dark"

[selection]
save_to_clipboard = true

[cursor.style]
blinking = "On"

[font]
size = 12

[font.bold]
family = "GeistMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font"
style = "Medium"

